default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: 5
  timeout: 5000
  username: agrihack
  password: agrihack
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: agrihack_development
  username: agrihack
  password: agrihack

test:
  <<: *default
  database: agrihack_test

production:
  <<: *default
  host: shilfy-dev.cp9hl8u2mcm6.ap-northeast-1.rds.amazonaws.com
  database: agrihack_production
  username: agrihack
  password: <%= ENV['DB_PASSWORD'] %>
